controllers-films-users
RomanDobrovolskiy/java-filmorate pull request #6
Opened 2022-05-21 09:12 UTC by RomanDobrovolskiy

Новая, исправленная версия (добавлены тесты и переделана валидация).

2022-05-22 10:08 UTC, Fleaman777 requested changes

2022-05-22 10:08 UTC, Fleaman777 commented on controllers-films-users/src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +                throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Фильм уже существует");
респонс при ошибки валидации неплохой, но это все же эксепшен, а контроллер по хорошему, не должен выкидывать эксепшены.
в качестве возвращаемого типа для методов контроллера можно использовать ResponseEntity<>. 
Специальная сущность в которую просечивается статус код, хэдеры, боди... 
baeldung.com/spring-response-entity

2022-05-22 10:08 UTC, Fleaman777 commented on controllers-films-users/src/test/java/ru/yandex/practicum/filmorate/tests/UserControllerTest.java
> +    }
тесты отличные, и круто что ты сделал все "по науке": тестируешь контроллеры путем отправки на них конкретных запросов с определенными данными, что бы проверить все тест кейсы.
но я хотел бы поделиться некоторой информацией:
В enterprise приложениях на java, особенно написанных на Spring, в ....ControllerTest обычно тестируется api - на контроллер приходят определенные запросы, и приложение отвечает определенным кодом и response body - такие тесты называются интеграционными, когда проверяется вся работа приложения, а не конкретные ее части(классы) как это происходит в юнит тестах.

Валидацию хорошо тестировать в обычных юнит тестах. Как раз, это будет проще сделать, если ее вынести в отдельный класс.

2022-05-23 16:27 UTC, RomanDobrovolskiy commented
feat: валидация разделена на методы для проведения тестов на валидацию
feat: изменено проведение тестов с помощью unit
feat: исправлены респонсы

2022-05-23 16:31 UTC, RomanDobrovolskiy commented on controllers-films-users/src/test/java/ru/yandex/practicum/filmorate/tests/UserControllerTest.java
> +    }
@Fleaman777 почему то в постмане тесты все проходит, а в гите кучу раз перезапускал, падает на подключении к серверу

2022-05-24 07:26 UTC, Fleaman777 commented on controllers-films-users/src/test/java/ru/yandex/practicum/filmorate/tests/UserControllerTest.java
> +    }
у тебя в checks в Run Application проверке не стартует приложение, похоже из-за того что не может скачать spring-boot-maven-plugin 
попробуй удалить вот эту строчку: <version>${project.parent.version}</version>

2022-05-24 07:36 UTC, Fleaman777 requested changes

2022-05-24 07:36 UTC, Fleaman777 commented on controllers-films-users/src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            filmValidator.durationValidation();
отлично, с такой проверкой контроллер стал выглядеть более правильно. 
но можно еще немного улучшить, 
в классе FilmValidator сделать 1 публичный метод validateFilm(film) который бы включал в себя все проверки, 
тогда в контроллере нам бы не пришлось вызывать все виды проверок фильма

с юзером можно провернуть то же самое

2022-05-24 07:36 UTC, Fleaman777 commented on controllers-films-users/src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotNull
здорово, что решил использовать такую аннотацию, 
в javax.validation.constraints есть еще всякие разные полезные аннотации

2022-05-24 07:36 UTC, Fleaman777 commented on controllers-films-users/src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(ex.getMessage());
это тоже чисто для информации: 

контроллер может выбрасывать исключения(а не толькот отдавать ResponseEntity), но желательно это делать тогда, когда в приложении есть ExceptionHandler, (https://www.baeldung.com/exception-handling-for-rest-with-spring)  - помогает отлавливать разные исключения из контроллера и выдавать соответсвующий респонс.
полезная фича спринга, думаю в  будущем ты обязательно ей будешь пользоваться

2022-05-24 07:37 UTC, Fleaman777 commented on controllers-films-users/src/test/java/ru/yandex/practicum/filmorate/tests/UserControllerTest.java
> +    }
@RomanDobrovolskiy если проблема не пофиксится, попробуй поискать в каких случаях бывает от еррор, который появляется в проверке "Run Application"

2022-05-24 08:59 UTC, RomanDobrovolskiy commented on controllers-films-users/src/test/java/ru/yandex/practicum/filmorate/tests/UserControllerTest.java
> +    }
@Fleaman777 ${project.parent.version} удалил но тесты падают на этапе Run Postman Tests
![изображение_2022-05-24_145718093](https://user-images.githubusercontent.com/97742909/169993232-03cf8901-65b8-4d67-8a86-45000a5e4ca8.png)

2022-05-24 13:40 UTC, Fleaman777 commented on controllers-films-users/src/test/java/ru/yandex/practicum/filmorate/tests/UserControllerTest.java
> +    }
к сожалению, работу с падающем чекером не могу принять, это дело надо пофиксить, 

@RomanDobrovolskiy попробуй из папки controllers-films-users перенести все на 1 уровень выше (так что бы папка src, pom.xml ... были все на одном уровне с gitignore, README..) в конченом итоге папка controllers-films-users должна быть пустой.

если этот вариант не поможет, напиши
спросим у кого-нибудь

2022-05-24 15:17 UTC, RomanDobrovolskiy commented on controllers-films-users/src/test/java/ru/yandex/practicum/filmorate/tests/UserControllerTest.java
> +    }
@Fleaman777 сейчас попробую

2022-05-24 15:48 UTC, RomanDobrovolskiy commented on controllers-films-users/src/test/java/ru/yandex/practicum/filmorate/tests/UserControllerTest.java
> +    }
@Fleaman777 все, удалось, помогло) скинул на ревью обновленную ссылку

2022-05-26 07:37 UTC, merged